apiVersion: v1
kind: Service
metadata:
  name: myweb-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: myweb
    release: stabel
  ports:
  - name: http
    port: 80
    targetPort: 9950