-- MySQL Script generated by MySQL Workbench
-- 04/01/18 11:57:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Transformer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Transformer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Transformer` DEFAULT CHARACTER SET gbk ;
USE `Transformer` ;

-- -----------------------------------------------------
-- Table `Transformer`.`productInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transformer`.`productInfo` (
  `product_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `product_name` VARCHAR(20) NOT NULL COMMENT '',
  `product_begintime` DATETIME(2) NOT NULL COMMENT '',
  `product_finishtime` DATETIME(2) NOT NULL COMMENT '',
  `product_state` VARCHAR(20) NOT NULL COMMENT '',
  `product_number` INT NOT NULL COMMENT '',
  `product_inductancevalue` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`product_id`)  COMMENT '',
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transformer`.`partCoordinateInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transformer`.`partCoordinateInfo` (
  `part_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `product_id` INT NOT NULL COMMENT '',
  `part1` VARCHAR(30) NULL COMMENT '',
  `part2` VARCHAR(30) NULL COMMENT '',
  `part3` VARCHAR(30) NULL COMMENT '',
  `part4` VARCHAR(30) NULL COMMENT '',
  `part5` VARCHAR(30) NULL COMMENT '',
  `part6` VARCHAR(30) NULL COMMENT '',
  INDEX `part_fk_idx` (`product_id` ASC)  COMMENT '',
  PRIMARY KEY (`part_id`)  COMMENT '',
  UNIQUE INDEX `part_id_UNIQUE` (`part_id` ASC)  COMMENT '',
  CONSTRAINT `part_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `Transformer`.`productInfo` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transformer`.`processTimeInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transformer`.`processTimeInfo` (
  `processTime_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `product_id` INT NOT NULL COMMENT '',
  `time1` DATETIME(2) NOT NULL COMMENT '',
  `time2` DATETIME(2) NOT NULL COMMENT '',
  `time3` DATETIME(2) NOT NULL COMMENT '',
  `time4` DATETIME(2) NOT NULL COMMENT '',
  `time5` DATETIME(2) NOT NULL COMMENT '',
  `time6` DATETIME(2) NOT NULL COMMENT '',
  INDEX `time_fk_idx` (`product_id` ASC)  COMMENT '',
  PRIMARY KEY (`processTime_id`)  COMMENT '',
  UNIQUE INDEX `processTime_id_UNIQUE` (`processTime_id` ASC)  COMMENT '',
  CONSTRAINT `time_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `Transformer`.`productInfo` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transformer`.`exceptionInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transformer`.`exceptionInfo` (
  `exception_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `product_id` INT NOT NULL COMMENT '',
  `type1` VARCHAR(30) NOT NULL COMMENT '',
  `type2` VARCHAR(30) NOT NULL COMMENT '',
  `type3` VARCHAR(30) NOT NULL COMMENT '',
  `type4` VARCHAR(30) NOT NULL COMMENT '',
  `type5` VARCHAR(30) NOT NULL COMMENT '',
  `type6` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`exception_id`)  COMMENT '',
  INDEX `exception_fk_idx` (`product_id` ASC)  COMMENT '',
  UNIQUE INDEX `exception_id_UNIQUE` (`exception_id` ASC)  COMMENT '',
  CONSTRAINT `exception_fk`
    FOREIGN KEY (`product_id`)
    REFERENCES `Transformer`.`productInfo` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Transformer`;

DELIMITER $$
USE `Transformer`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Transformer`.`productInfo_BEFORE_DELETE` BEFORE DELETE ON `productInfo` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
