FROM centos:centos7

RUN echo 'install environment'

RUN yum -y install tar wget gcc gcc-c++ libxml2-devel zlib-devel bzip2-devel curl-devel libjpeg-devel libpng-devel libtiff-devel freetype-devel openssl openssl-devel vim ncurses-devel cmake

