apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
  namespace: default
spec:
  containers:
  - name: lifecycle-demo-container
    image: my_hello_docker
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo test postStart > /tmp/lifecycle"]
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo test preStop > /tmp/lifecycle"]