apiVersion: v1 
kind: Pod  
metadata:
  name: readiness-httpget-pod 
  namespace: default
spec:  
  containers:  
  - name: readiness-httpget-container  
    image: my_hello_docker 
    imagePullPolicy: IfNotPresent
    readinessProbe:
      httpGet:
        port: 9950
        path: /posts
      initialDelaySeconds: 1
      periodSeconds: 5
    livenessProbe:
      exec:
        command: ["test","-e","/home/live"]
      initialDelaySeconds: 1
      periodSeconds: 30